---
- name: Install bash-completion and docker-compose on CentOS/RedHat
  yum:
    name:  "{{ item }}"
    state: present
  with_items:
    - bash-completion
    - docker-compose
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'
  
- name: Install bash-completion and docker-compose on Debian/Ubuntu
  yum:
    name:  "{{ item }}"
    state: present
  with_items:
    - bash-completion
    - docker-compose
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: downloading docker-compose...
  get_url:
    url: '{{docker_compose_url}}'
    dest: '{{docker_compose_install_dir}}/{{docker_compose_install_exe}}'
    checksum: '{{docker_compose_checksum}}'
    mode: 0755

- name: link /usr/local/bin/docker-compose
  file:
    src: '{{docker_compose_install_dir}}/{{docker_compose_install_exe}}'
    dest: '{{docker_compose_install_dir}}/docker-compose'
    state: link

- name: install bash completions...
  get_url:
    url: https://raw.githubusercontent.com/docker/compose/master/contrib/completion/bash/docker-compose
    dest: '{{docker_compose_bash_completion_d}}/docker-compose.sh'
    mode: 0644
