version: '2'
services:
  postgresql:
    image: {{ postgresql_image }}
    volumes:
      - ./data/pg:/var/lib/postgresql

  coturn:
    image: {{ turn_image }}
    network_mode: host
    environment:
      - TURN_USERNAME=dialog
      - TURN_PASSWORD=dialog
      - TURN_PORT=3478
      - REALM=dialog

  dialog-server:
    image: {{ dlg_image }}
    # command: /opt/docker/bin/dialog-enterprise -DDB_REPAIR=true
    volumes:
      - ./conf:/opt/docker/conf:ro
      - ./data/server/files:/storage/files
    ports:
      - 127.0.0.1:9090:9090
      - 127.0.0.1:9080:9080
      - 127.0.0.1:9070:9070
    links:
      - postgresql
    depends_on:
      - postgresql

  web-app:
    image: {{ web_app_image }}
    ports:
      - 127.0.0.1:{{ web_app_port }}:80

  dashboard:
    image: {{ dashboard_image }}
    environment:
      - ENDPOINT=http://dialog-server:9090
    ports:
      - 127.0.0.1:{{ dashboard_port }}:3000
    links:
      - dialog-server

#  invites:
#    image: {{ invite_image }}
#    environment:
#      - ENDPOINT=http://dialog-server:9090
#      - ENDPOINT_AUTH=admin:{{ admin_password }}
#      - WEBLINK={{ http_scheme }}://{{ base_url }}
#    ports:
#      - 127.0.0.1:8081:8080
#    links:
#      - dialog-server
