---
- name: Install packages on Debian/Ubuntu
  apt:
    name:  "{{ item }}"
    state: present
    install_recommends: false
    update_cache:       true
    cache_valid_time:   3600
  with_items:
    - netcat
    - curl
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: Install packages on CentOS/RedHat
  yum:
    name:  "{{ item }}"
    state: present
    update_cache:       true
  with_items:
    - nmap-ncat
    - curl
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'
