---
- name: Install NGINX on Debian/Ubuntu
  apt:
    name:  "{{ item }}"
    state: present
    install_recommends: false
    update_cache:       true
    cache_valid_time:   3600
  with_items:
    - nginx
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: Install NGINX on CentOS/RedHat
  yum:
    name:  "{{ item }}"
    state: present
    update_cache:       true
  with_items:
    - nginx
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

- include_tasks: dhparam.yml
  when: use_tls

- name: Copy the nginx configuration file
  template:
    src: nginx.conf.j2
    dest: "{{ nginx_conf_dir }}/nginx.conf"
  notify:
   - nginx restart
  tags: nginx_reconf

- import_tasks: sites.yml
  tags: nginx_reconf
