---
- name: Install NGINX
  apt:
    name:  "{{ item }}"
    state: present
    install_recommends: false
    update_cache:       true
    cache_valid_time:   3600
  with_items:
    - nginx

- include_tasks: dhparam.yml
  when: use_tls

- name: Copy the nginx configuration file
  template:
    src: nginx.conf.j2
    dest: "{{ nginx_conf_dir }}/nginx.conf"
  notify:
   - nginx restart
  tags: nginx_reconf

- import_tasks: sites.yml
  tags: nginx_reconf
