---
- name: Install NGINX
  apt:
    name:  "{{ item }}"
    state: present
    install_recommends: false
    update_cache:       true
    cache_valid_time:   3600
  with_items:
    - nginx

- include_tasks: dhparam.yml
  when: use_tls

- name: Copy the nginx configuration file
  template:
    src: nginx.conf.j2
    dest: "{{ nginx_conf_dir }}/nginx.conf"
  notify:
   - nginx restart
  tags: nginx_reconf

- set_fact:
    letsencrypt_domain: "{{ base_url }}"
    letsencrypt_request_www: false
    letsencrypt_pause_services:
      - nginx
  when: use_letsencrypt

- include_role:
    name: letsencrypt
  when: use_letsencrypt and use_tls

- import_tasks: sites.yml
  tags: nginx_reconf
