---
nginx_http_default_params:
  - sendfile on
  - tcp_nopush on
  - tcp_nodelay on
  - keepalive_timeout 70
  - "access_log {{nginx_log_dir}}/access.log"
  - "error_log {{nginx_log_dir}}/error.log {{nginx_error_log_level}}"
  - server_tokens off
  - types_hash_max_size 2048
  - log_format comb '$remote_addr - $remote_user [$time_local]  '
                    '"$request" $status $body_bytes_sent '
                    '"$http_referer" "$http_user_agent"'
  - gzip_static on
  - gzip on
  - gzip_disable "msie6"
